import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { stripeClient } from '../src/providers.js';
const base = 'https://david-shirt-shop.david-shirt-shop.workers.dev';
const origin = 'https://davidsshapiro.com';
const request = (path, options = {}) => fetch(`${base}${path}`, { ...options, signal: AbortSignal.timeout(60000) });
const health = await request('/api/health'); assert.equal(health.status, 200);
const productResponse = await request('/api/product', { headers: { Origin: origin } });
if (productResponse.status !== 200) console.log(JSON.stringify({ productError: productResponse.headers.get('X-Shop-Error-Code'), upstreamStatus: productResponse.headers.get('X-Upstream-Status') }));
assert.equal(productResponse.status, 200);
assert.equal(productResponse.headers.get('Access-Control-Allow-Origin'), origin);
const catalog = await productResponse.json();
assert.equal(catalog.available, true);
assert.equal(catalog.product.checkoutEnabled, false);
assert.equal(catalog.product.variants.length, 28);
assert.ok(catalog.product.variants.every(v => v.price === 2000));
assert.equal(catalog.product.shipping, 495);
assert.deepEqual(catalog.product.countries, ['US']);
const closed = await request('/api/checkout', { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json' }, body: '{}' });
assert.equal(closed.status, 503);
const foreign = await request('/api/checkout', { method: 'POST', headers: { Origin: 'https://example.com', 'Content-Type': 'application/json' }, body: '{}' });
assert.equal(foreign.status, 403);
const payload = JSON.stringify({ id: 'evt_shop_connection_check', type: 'shop.connection_check', livemode: false, data: { object: {} } });
const signature = stripeClient(process.env).webhooks.generateTestHeaderString({ payload, secret: process.env.STRIPE_WEBHOOK_SECRET });
const valid = await request('/api/stripe/webhook', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Stripe-Signature': signature }, body: payload });
assert.equal(valid.status, 200);
const invalid = await request('/api/stripe/webhook', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Stripe-Signature': 'invalid' }, body: payload });
assert.equal(invalid.status, 400);
await mkdir('.local', { recursive: true });
await writeFile('.local/deployed-product.json', JSON.stringify(catalog, null, 2));
// A public, display-only fallback. It can never enable checkout.
await writeFile('../assets/shop/product.json', JSON.stringify({ ...catalog, product: { ...catalog.product, checkoutEnabled: false } }, null, 2));
console.log(JSON.stringify({ passed: ['health', 'product_prices', 'US_shipping', 'CORS', 'checkout_closed', 'foreign_origin_rejected', 'signed_webhook', 'forged_webhook_rejected'], product: catalog.product.title, variants: catalog.product.variants.length, sizeGuide: Boolean(catalog.product.sizeGuide) }));
